export const sampleData = [
    {
        id: 0, 
        code: '35655',
        name: 'ICS 46',
        location: 'ELH 100',
        time: '9-9:50AM',
        start: 9,
        type: 'LEC',
        days: ['Monday', 'Wednesday', 'Friday'],
    },
    {
        id: 1, 
        code: '35656',
        name: 'ICS 46',
        location: 'HH 278',
        time: '2-2:50PM',
        start: 14,
        type: 'DIS',
        days: ['Monday', 'Wednesday'],
    },
    {
        id: 2, 
        code: '28120',
        name: 'H 1B',
        location: 'HIB 100',
        time: '9:30-10:50AM',
        start: 9,
        type: 'LEC',
        days: ['Tuesday', 'Thursday'],
    },
    {
        id: 3, 
        code: '28122',
        name: 'H 1BS',
        location: 'HH 214',
        time: '3:30-4:50PM',
        start: 15,
        type: 'SEM',
        days: ['Tuesday', 'Thursday'],
    },
    {
        id: 4, 
        code: '35600',
        name: 'ICS 33',
        location: 'EH 1200',
        time: '5:00-6:20PM',
        start: 17,
        type: 'LEC',
        days: ['Tuesday', 'Thursday'],
    },
    {
        id: 5, 
        code: '35615',
        name: 'ICS 33',
        location: 'ICS 364',
        time: '2:00-3:20PM',
        start: 14,
        type: 'LAB',
        days: ['Monday', 'Wednesday', 'Friday'],
    },
    {
        id: 6, 
        code: '35530',
        name: 'ICS 6D',
        location: 'HIB 100',
        time: '11:00-11:50AM',
        start: 14,
        type: 'LEC',
        days: ['Monday', 'Wednesday', 'Friday'],
    },
    {
        id: 7, 
        code: '35532',
        name: 'ICS 6D',
        location: 'MSTB 118',
        time: '1:00-1:50PM',
        start: 13,
        type: 'DIS',
        days: ['Monday', 'Wednesday'],
    },
]